name: auto_exit_process
description: An auto exit Process in Windows platform.
repository: https://github.com/KuiyuanFu/auto_exit_process
version: 0.0.0+0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  path: ^1.8.0
  ffi: ^2.0.1
  win32: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
